import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./components/StyledComponentsRegistry";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const runtime = "edge";

export const metadata: Metadata = {
  title: "Movies BATMAN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased bg-[#0f0f0f] text-white`}>
        {/* load AdSense runtime after the page is interactive */}
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
